name: JSDoc Generation

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          output_dir: ./source/docs
          recurse: false
          template: minami
          front_page: README.md

      - name: Manual JSDoc
        run: "npm install jsdoc; npx jsdoc -r -d $GITHUB_WORKSPACE/source/docs $GITHUB_WORKSPACE/source/*.js "
